# NumPy

When you work with python (and with whatever other programming language actually), it is mandatory to know the instrument you are using.
It is a matter of efficiency, both in terms of **SOFTWARE** as well as **WETWARE**.

In [1]:
import numpy

It is not standard but it is almost as it was in scientific computing using the Python programming language.

> **DO NOT RE-INVENT THE WHEEL**

It is built 
* to provide an efficient, intuitive and pythonic interface to Numerical computation
* to bridge a gap between compiled-language standards on memory management
* to simplify the user's life

**Implements A LOT of analytical functions and useful values** (very well optimised)

Some examples:

* logarithms and exponentials (i.e. ``numpy.exp``,``numpy.log``,``numpy.log10``)
* trigonometric functions (e.g. ``numpy.sin``, ``numpy.cos``, and the inverse functions, and the hyperbolic versions)
* statistical functions (e.g. ``numpy.mean``, ``numpy.std``)
* mathematical constants (e.g. ``numpy.pi``, ``numpy.e``)

## Array programming

The building-block data-structure in NumPy is the N-dimensional array:

* **constructors**

In [2]:
# Il contenuto degli array è omogeneo: tutti gli elementi dello stesso tipo.

In [5]:
ar_from_shape = numpy.ndarray((2,3))
type(ar_from_shape), ar_from_shape

(numpy.ndarray,
 array([[5.40162779e-310, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]))

In [8]:
ar_from_obj = numpy.array((2.,3)) 
# un caster: trasforma qualunque container in un array di numpy, purché sia omogeneo (se non lo è lo rende tale, in maniera non so come definita.)
type(ar_from_obj), ar_from_obj

(numpy.ndarray, array([2., 3.]))

and also:
* ``numpy.linspace``, ``numpy.logspace``, ``numpy.arange``
* ``numpy.ones``, ``numpy.zeros``, ``numpy.empty``
* ``numpy.ones_like``, ``numpy.zeros_like``, ``numpy.empty_like``

* **casting functions**

In [9]:
ls1 = [ 1, 2, 3 ]
ar_from_ls = numpy.asarray(ls1) # <------
type(ar_from_ls), ar_from_ls

(numpy.ndarray, array([1, 2, 3]))

In [10]:
ls2 = [ ls1, ls1 ]
ar_from_ls_cont = numpy.ascontiguousarray(ls2) # <------
type(ar_from_ls_cont), ar_from_ls_cont

(numpy.ndarray,
 array([[1, 2, 3],
        [1, 2, 3]]))

contiguity in memory is not guaranteed on the 1st dimension if you use ``numpy.array`` to cast something as above

In [11]:
ar_from_ls_cont[0] is ar_from_ls_cont[1]

False

**MAIN CHARACTERISTICS**

* uniform type: you should not use NDarrays to cast something like this

In [12]:
ar = numpy.array([1, 'hello', True])

In [13]:
ar.dtype, ar

(dtype('<U21'), array(['1', 'hello', 'True'], dtype='<U21'))

* N-dimensional

In [14]:
diag1 = numpy.array( 
    [[1, 0],
     [0, 1]]
)
diag1.shape, diag1.size

((2, 2), 4)

> **NOTE** that for the specific matrix we have built above there are specific functions
>```python
> >>> numpy.diag((1,1))
>```
>```
>array([[1, 0],
>       [0, 1]])
>```
>```python
> >>> numpy.identity(2)
>```
>```
>array([[1, 0],
>       [0, 1]])
>```

and specific functions to perform operations on it, e.g.

In [15]:
diag1.diagonal()

array([1, 1])

* **Broadcasting** (vectorisation): at [this link](https://numpy.org/doc/stable/user/basics.broadcasting.html) the NumPy guide

In [18]:
a = numpy.array([[1, 2, 3],
                [4, 5, 6]])


In [19]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
# BROADCASTING inizia da qui

In [23]:
ar1 = numpy.array( [1,2,3,4] )

In [24]:
# scalar operations
ar1 * 10

array([10, 20, 30, 40])

In [25]:
# same size arrays
ar2 = numpy.array([4, 3, 2, 1])
ar1 + ar2

array([5, 5, 5, 5])

In [26]:
# more complex shapes
mat = numpy.array(
    [[1, 2, 3, 4], 
     [5, 6, 7, 8]]
)
mat + ar1

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [27]:
# but the order of the dimensions count
mat.T + ar1

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

So what happens when we have to broadcast an array-operation to some other array with different size?  

In [29]:
x = numpy.array([1,2,3,4,5])
y = numpy.logspace(0,6,7) # una sequenza di numeri equispaziati se prendo il logaritmo. è un array di dimensione 7
x, x.size, y, y.size

(array([1, 2, 3, 4, 5]),
 5,
 array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06]),
 7)

In [31]:
x*y 

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

**CANNOT BE BROADCASTED!**

But let's say I want to build a matrix in which each line is the result of the product of an element from the first array (``x``) and the second array (``y``), having therefore dimensions $5\times7$ 

In [32]:
x.T * y

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

We have the possibility to increase the number of axis of the first array

In [33]:
x[:, numpy.newaxis] #aggiunge una dimensione fittizia. Questo comando prende tutto nella prima dimensione, più un nuovo asse nell'altra dimensione.

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [34]:
# Un asse libero è come uno scalare, e lo scalare sa già come farne broadcasting.

In [35]:
xy = x[:, numpy.newaxis]*y
xy, xy.shape

(array([[1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06],
        [2.e+00, 2.e+01, 2.e+02, 2.e+03, 2.e+04, 2.e+05, 2.e+06],
        [3.e+00, 3.e+01, 3.e+02, 3.e+03, 3.e+04, 3.e+05, 3.e+06],
        [4.e+00, 4.e+01, 4.e+02, 4.e+03, 4.e+04, 4.e+05, 4.e+06],
        [5.e+00, 5.e+01, 5.e+02, 5.e+03, 5.e+04, 5.e+05, 5.e+06]]),
 (5, 7))

Or, if we want to do it the other way round:

In [38]:
yx = x*y[:, numpy.newaxis] 
# il * fra due array fa sempre il prodotto elemento per elemento. 
# La moltiplicazione riga per colonna si fa in altro modo (chiedi a gpt come).
yx, yx.shape

(array([[1.e+00, 2.e+00, 3.e+00, 4.e+00, 5.e+00],
        [1.e+01, 2.e+01, 3.e+01, 4.e+01, 5.e+01],
        [1.e+02, 2.e+02, 3.e+02, 4.e+02, 5.e+02],
        [1.e+03, 2.e+03, 3.e+03, 4.e+03, 5.e+03],
        [1.e+04, 2.e+04, 3.e+04, 4.e+04, 5.e+04],
        [1.e+05, 2.e+05, 3.e+05, 4.e+05, 5.e+05],
        [1.e+06, 2.e+06, 3.e+06, 4.e+06, 5.e+06]]),
 (7, 5))

This is the **MOST IMPORTANT FEATURE OF NUMPY** 

And if you are not, you can go back to not using numpy at all (I have shown you the tools are already there)

Little demonstration:

In [39]:
X = numpy.linspace(1,int(1e+3),int(1e+3))
Y = numpy.logspace(0, 6, int(1.e+4))

In [40]:
%%time
out = []
for x in X :
    tmp = []
    for y in Y :
        tmp += [x * y]
    out += [tmp]
out = numpy.array(out)

CPU times: user 2.78 s, sys: 90.8 ms, total: 2.87 s
Wall time: 2.87 s


In [41]:
%time out = numpy.array([[x*y for y in Y] for x in X])
out.shape

CPU times: user 1.41 s, sys: 80.7 ms, total: 1.49 s
Wall time: 1.49 s


(1000, 10000)

In [44]:
%time out = X[:,numpy.newaxis]*Y

CPU times: user 6.87 ms, sys: 1.05 ms, total: 7.92 ms
Wall time: 7.08 ms


In [45]:
# Il broadcasting è estremamente efficiente. Qui sta il saper usare bene numpy

#### Some CAVEATS

> **WARNING** Even though uniform

In [46]:
class custom () :
    def __init__ ( self, num ) :
        self.num = num
    def __repr__ ( self ) :
        return f'custom({self.num})'
    def __str__ (self) :
        return self.__repr__()

In [47]:
numpy.array( [ custom( i ) for i in range(3) ] )

array([custom(0), custom(1), custom(2)], dtype=object)

It's saved as a generic *object* type

In [ ]:
ar_custom = numpy.array( [ custom( i ) for i in range(3) ] )
ar_custom *= 2

**NumPy is not thought to do this kind of stuff**

Even though you could work around the error above:

```python
    class custom () :
        def __init__ ( self, num ) :
            self.num = num
        def __repr__ ( self ) :
            return f'custom({self.num})'
        def __str__ (self) :
            return self.__repr__()
        def __mul__ (self, other) :
            return self.num * other
        def __imul__ ( self, other ) :
            return self.__mul__(other)
```

It is discouraged, because you won't know what other NumPy behaviour cannot be given to the custom object.

> **NUMPY IS FOR PRIMORDIAL NUMERICAL VARIABLE TYPES**
>
> for custom objects better use other containers or organising the data differently

### BUT WITH A BIT OF AWARENESS YOU CAN MAKE YOUR FUNCTIONS NUMPY COMPLIANT

Which means that you want to favour broadcasting when you implement something:

In [ ]:
def func_naive (x, y=10) :
    from math import exp
    return exp(x)/y

In [ ]:
X = numpy.linspace(0.0,1.0,100)

In [ ]:
func_naive(X)

In [ ]:
%time fx = [func_naive(x) for x in X]

In [ ]:
def func_numpy (x, y=10) :
    from numpy import exp
    return exp(x)/y

In [ ]:
%time fx = func_numpy(X)

**what about the second argument?**

We have to make a choice, depending on the problem at end:

* maybe the desired behaviour is to only accept scalars, then we should check for it

In [ ]:
def func_numpy_yscalar (x, y=10) :
    from numpy import exp
    if hasattr( y, '__len__' ) :
        raise TypeError( 'argument `y` should be a scalar' )
    return exp(x)/y

* maybe instead we want it to
    - accept scalars
    - accept arrays of the same dimension
    - broadcast automathically

In [ ]:
def func_numpy_ybroadcast (x, y=10) :
    import numpy 
    # careful because these will also make copies
    x = numpy.array(x)
    y = numpy.array(y)
    # store if the inputs were scalar
    xscalar = False
    if x.ndim == 0 :
        x = x[None]
        xscalar = True
    yscalar = False
    if y.ndim == 0 :
        y = y[None]
        yscalar = True
    # add an axis if necessary
    if not xscalar|yscalar and y.size != x.size :
        x = x[:,numpy.newaxis]
    ret = numpy.exp(x) / y
    # if scalar input return a scalar
    if xscalar & yscalar :
        return ret.item()
    return ret

In [ ]:
a = func_numpy_ybroadcast( X )
b = func_numpy_ybroadcast( 1, numpy.linspace(1.,2.,X.size) )
c = func_numpy_ybroadcast( X, numpy.linspace(1.,2.,X.size) )
d = func_numpy_ybroadcast( X, [1, 2, 3] )
a.shape, b.shape, c.shape, d.shape

We have though lost something for being able to do this:

In [ ]:
func_numpy_ybroadcast(1,2)

Can you tell me what the problem is with this implementation?

### One last point on arrays: indexing and masking

In [48]:
ar = numpy.arange(0, 100, 11)

In [49]:
ar

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

#### An array can be indexed:

* with a single index

In [50]:
ar[3]

np.int64(33)

* with a sequence of indexes

In [51]:
indexes = [0, 3, 5]

In [52]:
ar[indexes]

array([ 0, 33, 55])

#### An array can be sliced: ``a[start:stop:step]``

* from the head

In [53]:
ar[:3]

array([ 0, 11, 22])

* from the tail

In [54]:
ar[-3:]

array([77, 88, 99])

* in the middle

In [55]:
ar[3:6]

array([33, 44, 55])

* with some step

In [56]:
ar[1:-1:2]

array([11, 33, 55, 77])

#### An array can be masked

In [57]:
weven = (ar%2 == 0) 
# un array di 0 e 1 della stessa dimensione dell'array che voglio mascherare. Scelgo quali elementi prendere e quali no (qui prende quelli pari)

A mask is a boolean array with the same dimension of the object you want to mask

In [58]:
weven

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
ar[weven] 
# se la passo come indice dell'array originale ho un array con solo gli elementi pari. nota: non è una copia, è lo stesso array di cui sto vedendo solo gli elementi pari.

array([ 0, 22, 44, 66, 88])

#### and the mask can be inverted

In [61]:
ar[~weven]

array([11, 33, 55, 77, 99])

#### and two masks can be combined

In [62]:
wmaj50 = ( ar > 50 )

In [67]:
wmaj50

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
ar[weven&wmaj50]

array([66, 88])

In [69]:
wdiv3 = (ar%3 == 0)

In [70]:
ar[weven|wdiv3]

array([ 0, 22, 33, 44, 66, 88, 99])

#### And all of this can be done also on matrices with a bit more care

In [71]:
mat = (ar[:, numpy.newaxis]) * numpy.flip(ar+1)

In [72]:
mat = mat[1:]
mat, mat.shape

(array([[1100,  979,  858,  737,  616,  495,  374,  253,  132,   11],
        [2200, 1958, 1716, 1474, 1232,  990,  748,  506,  264,   22],
        [3300, 2937, 2574, 2211, 1848, 1485, 1122,  759,  396,   33],
        [4400, 3916, 3432, 2948, 2464, 1980, 1496, 1012,  528,   44],
        [5500, 4895, 4290, 3685, 3080, 2475, 1870, 1265,  660,   55],
        [6600, 5874, 5148, 4422, 3696, 2970, 2244, 1518,  792,   66],
        [7700, 6853, 6006, 5159, 4312, 3465, 2618, 1771,  924,   77],
        [8800, 7832, 6864, 5896, 4928, 3960, 2992, 2024, 1056,   88],
        [9900, 8811, 7722, 6633, 5544, 4455, 3366, 2277, 1188,   99]]),
 (9, 10))

* slice in one of the two dimensions

In [73]:
mat[2,:]

array([3300, 2937, 2574, 2211, 1848, 1485, 1122,  759,  396,   33])

In [74]:
mat[:,3]

array([ 737, 1474, 2211, 2948, 3685, 4422, 5159, 5896, 6633])

* mask along all dimensions

In [75]:
mat[mat%2==0]

array([1100,  858,  616,  374,  132, 2200, 1958, 1716, 1474, 1232,  990,
        748,  506,  264,   22, 3300, 2574, 1848, 1122,  396, 4400, 3916,
       3432, 2948, 2464, 1980, 1496, 1012,  528,   44, 5500, 4290, 3080,
       1870,  660, 6600, 5874, 5148, 4422, 3696, 2970, 2244, 1518,  792,
         66, 7700, 6006, 4312, 2618,  924, 8800, 7832, 6864, 5896, 4928,
       3960, 2992, 2024, 1056,   88, 9900, 7722, 5544, 3366, 1188])

Oh no! it has been flattened! This is because not all the lines had the same size.

**be careful of the I/Os when you mask!**

In [76]:
mask4lines = numpy.ones_like(mat[:,0], dtype=bool)
mask4lines[-4:] = False
mask4lines

array([ True,  True,  True,  True,  True, False, False, False, False])

In [77]:
mat[mask4lines]

array([[1100,  979,  858,  737,  616,  495,  374,  253,  132,   11],
       [2200, 1958, 1716, 1474, 1232,  990,  748,  506,  264,   22],
       [3300, 2937, 2574, 2211, 1848, 1485, 1122,  759,  396,   33],
       [4400, 3916, 3432, 2948, 2464, 1980, 1496, 1012,  528,   44],
       [5500, 4895, 4290, 3685, 3080, 2475, 1870, 1265,  660,   55]])

In [78]:
mask4cols = numpy.ones_like(mat[0], dtype=bool)
mask4cols[-4:] = False
mask4cols

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [79]:
mat[:,mask4cols]

array([[1100,  979,  858,  737,  616,  495],
       [2200, 1958, 1716, 1474, 1232,  990],
       [3300, 2937, 2574, 2211, 1848, 1485],
       [4400, 3916, 3432, 2948, 2464, 1980],
       [5500, 4895, 4290, 3685, 3080, 2475],
       [6600, 5874, 5148, 4422, 3696, 2970],
       [7700, 6853, 6006, 5159, 4312, 3465],
       [8800, 7832, 6864, 5896, 4928, 3960],
       [9900, 8811, 7722, 6633, 5544, 4455]])

## Random

NumPy implements **(pseudo-)RANDOM NUMBER GENERATORS** in the sub-package ``numpy.random`` ([here the docs](https://numpy.org/doc/stable/reference/random/index.html)).

Generating random numbers is extremely useful in science for a lot of cases.

In [ ]:
rng = numpy.random.default_rng( seed = 555 )

> **NOTE THAT** I am using a ``seed`` for **reproducibility**

Random number generation is embedded in the array-programming framework of NumPy:

* **uniform distributions**

In [ ]:
rng.uniform(size=10)

In [ ]:
help(rng.uniform)

In [ ]:
rng.integers(1, size=10, endpoint=True)

* **non-uniform distributions**

In [ ]:
rng.normal(size=10)

In [ ]:
rng.poisson(size=10)

### EXERCISE: sample from a custom non-uniform distribution

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def custom_cdf ( x ) :
    return 1-(0.5 * ( numpy.cos(x) + 1 ) )

In [ ]:
x = numpy.linspace(0, numpy.pi, 1024)
fx = custom_cdf(x)

In [ ]:
plt.plot(x, fx)

In [ ]:
ydata = numpy.interp( 
    rng.uniform(size=4096), 
    fx,
    x
)

In [ ]:
ydata

In [ ]:
yhist, xbins = numpy.histogram(ydata, bins=(10))

In [ ]:
ycums = yhist.cumsum()/ydata.size

In [ ]:
plt.plot(x, fx)
plt.step(xbins[1:], ycums)

Are they the same distribution???

(you can try to increase the number of bins in the function above (e.g. ``numpy.histogram( ydata, bins=(100) )``)

In [ ]:
from scipy.stats import kstest
kstest(ydata, custom_cdf).pvalue > 0.05

**what about a PDF??**

In [ ]:
def custom_pdf ( x ) :
    return x * numpy.exp(-x)

**you can try this yourself**